use_frameworks!

platform :ios, '8.0'

target 'YSYRouter_Example' do
  pod 'YSYRouter', :path => '../'

#  target 'YSYRouter_Tests' do
#    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#   pod 'Expecta+Snapshots'
#  end
end
